/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMatchRouteImport } from './routes/api.match'
import { Route as ApiFontRouteImport } from './routes/api.font'
import { Route as ApiExtractFontsRouteImport } from './routes/api.extract-fonts'
import { Route as ApiExtractRouteImport } from './routes/api.extract'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchRoute = ApiMatchRouteImport.update({
  id: '/api/match',
  path: '/api/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFontRoute = ApiFontRouteImport.update({
  id: '/api/font',
  path: '/api/font',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractFontsRoute = ApiExtractFontsRouteImport.update({
  id: '/api/extract-fonts',
  path: '/api/extract-fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/extract-fonts': typeof ApiExtractFontsRoute
  '/api/font': typeof ApiFontRoute
  '/api/match': typeof ApiMatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/extract-fonts': typeof ApiExtractFontsRoute
  '/api/font': typeof ApiFontRoute
  '/api/match': typeof ApiMatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/extract-fonts': typeof ApiExtractFontsRoute
  '/api/font': typeof ApiFontRoute
  '/api/match': typeof ApiMatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/extract'
    | '/api/extract-fonts'
    | '/api/font'
    | '/api/match'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/extract' | '/api/extract-fonts' | '/api/font' | '/api/match'
  id:
    | '__root__'
    | '/'
    | '/api/extract'
    | '/api/extract-fonts'
    | '/api/font'
    | '/api/match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiExtractFontsRoute: typeof ApiExtractFontsRoute
  ApiFontRoute: typeof ApiFontRoute
  ApiMatchRoute: typeof ApiMatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match': {
      id: '/api/match'
      path: '/api/match'
      fullPath: '/api/match'
      preLoaderRoute: typeof ApiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/font': {
      id: '/api/font'
      path: '/api/font'
      fullPath: '/api/font'
      preLoaderRoute: typeof ApiFontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-fonts': {
      id: '/api/extract-fonts'
      path: '/api/extract-fonts'
      fullPath: '/api/extract-fonts'
      preLoaderRoute: typeof ApiExtractFontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiExtractFontsRoute: ApiExtractFontsRoute,
  ApiFontRoute: ApiFontRoute,
  ApiMatchRoute: ApiMatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
